### ISSUE TITLE
everything looks okay but doesnt work

### ISSUE THREAD

**Issue by gerdal91** [har-in-air/ESP8266_MPU9250_MS5611_VARIO#2]
Hello , first thank you for sharing your code. I build one for me everything looks okay but doesnt work 
it beeps it calibrate  then say start vario but doesnt beep

Battery voltage = 0.1V

Checking communication with MS5611
MS5611 PROM CRC = 0xe
Calculated CRC = 0xe
MS5611 OK

Checking communication with MPU9250
MPU9250 OK
Calibration parameters from NVD
Accel : axBias -703, ayBias 358, azBias -151
Gyro : gxBias -41, gyBias -33, gzBias -25
Counting down to gyro calibration
Press the pgmconfcal button if accelerometer calibration is also required
10
9
8
7
6
5
4
3
2
1

Calibrating gyro
Num Tries = 3
gxBias = -42
gyBias = -31
gzBias = -25
Gyro calibration OK

MS5611 config
MS5611 Calibration Coeffs : 47112 49478 29596 27406 31055 28384
Tavg : 24C
Pavg : 92534Pa
Zavg : 75887cm

KalmanFilter config
zMeasVariance 300
zAccelVariance 50000

Vario beeper config
climbToneCps = 20
zeroesToneCps = 0
sinkToneCps = -200
crossoverCps = 400

Start vario

**Comment by har-in-air** [comment]
Try putting some diagnostic code in the loop to toggle an led or print a character to serial port so that you know its not hanging waiting for the DRDY signal from the MPU9250. 
If it is hanging, check that the DRDY signal is pulsing with a scope, if that is OK, you could have a bad connection from DRDY to the ESP8266.

**Comment by gerdal91** [comment]
Thank you I figured I found I didn't wire the int pin on mpu9250

GÖKHAN ERDAL

**Comment by gerdal91** [comment]
Hello I have 2 more questions.
1. My vario beeps even with no movement with a period 
2. How can I serial print the vario speed  and altitude? I know I need to put in the loop but what I need to put ? 

GÖKHAN ERDAL

**Comment by har-in-air** [comment]
1.  Normal, there is sensor noise.2.  You can't, the code in the loop needs to execute within 2mS because of the sensor sample rate of 500Hz. Print statements take a long time.
    On Wednesday, 8 April, 2020, 11:21:51 am IST, gökhan erdal <notifications@github.com> wrote:  
 
 

Hello I have 2 more questions.
1. My vario beeps even with no movement with a period 
2. How can I serial print the vario speed and altitude? I know I need to put in the loop but what I need to put ? 

GÖKHAN ERDAL

**Comment by gerdal91** [comment]
It doesn’t beeb like in your Video I will record a video tonight

8 Nis 2020 Çar, saat 09:27 tarihinde Hari Nair <notifications@github.com>
şunu yazdı:

> 1.  Normal, there is sensor noise.2.  You can't, the code in the loop
> needs to execute within 2mS because of the sensor sample rate of 500Hz.
> Print statements take a long time.
> On Wednesday, 8 April, 2020, 11:21:51 am IST, gökhan erdal <

**Comment by har-in-air** [comment]
If you use a beep threshold of 0, it will beep, because 50 percent of the time, the value will be above 0 !

Sent from Yahoo Mail on Android 
 
  On Wed, 8 Apr 2020 at 12:54, gökhan erdal<notifications@github.com> wrote:   

It doesn’t beeb like in your Video I will record a video tonight

8 Nis 2020 Çar, saat 09:27 tarihinde Hari Nair <notifications@github.com>
şunu yazdı:

> 1. Normal, there is sensor noise.2. You can't, the code in the loop
> needs to execute within 2mS because of the sensor sample rate of 500Hz.
> Print statements take a long time.
> On Wednesday, 8 April, 2020, 11:21:51 am IST, gökhan erdal <

**Comment by gerdal91** [comment]
I use your default configuration .

8 Nis 2020 Çar, saat 10:27 tarihinde Hari Nair <notifications@github.com>
şunu yazdı:

> If you use a beep threshold of 0, it will beep, because 50 percent of the
> time, the value will be above 0 !
>
> Sent from Yahoo Mail on Android
>
> On Wed, 8 Apr 2020 at 12:54, gökhan erdal<notifications@github.com>
> wrote:
>
> It doesn’t beeb like in your Video I will record a video tonight
>
> 8 Nis 2020 Çar, saat 09:27 tarihinde Hari Nair <notifications@github.com>
> şunu yazdı:
>
> > 1. Normal, there is sensor noise.2. You can't, the code in the loop
> > needs to execute within 2mS because of the sensor sample rate of 500Hz.
> > Print statements take a long time.
> > On Wednesday, 8 April, 2020, 11:21:51 am IST, gökhan erdal <

**Comment by har-in-air** [comment]
Also, for the demo videos, the audio is programmed to show off the sensitivity of the instrument. Not for paragliding.  You can always change the tonal scale for your application and  liking.

Sent from Yahoo Mail on Android 
 
  On Wed, 8 Apr 2020 at 12:54, gökhan erdal<notifications@github.com> wrote:   

It doesn’t beeb like in your Video I will record a video tonight

8 Nis 2020 Çar, saat 09:27 tarihinde Hari Nair <notifications@github.com>
şunu yazdı:

> 1. Normal, there is sensor noise.2. You can't, the code in the loop
> needs to execute within 2mS because of the sensor sample rate of 500Hz.
> Print statements take a long time.
> On Wednesday, 8 April, 2020, 11:21:51 am IST, gökhan erdal <

**Comment by har-in-air** [comment]
For the kalman filter demo video I put this info about the tonal scale in the video description.  

Sent from Yahoo Mail on Android 
 
  On Wed, 8 Apr 2020 at 13:05, gökhan erdal<notifications@github.com> wrote:   

I use your default configuration .

8 Nis 2020 Çar, saat 10:27 tarihinde Hari Nair <notifications@github.com>
şunu yazdı:

> If you use a beep threshold of 0, it will beep, because 50 percent of the
> time, the value will be above 0 !
>
> Sent from Yahoo Mail on Android
>
> On Wed, 8 Apr 2020 at 12:54, gökhan erdal<notifications@github.com>
> wrote:
>
> It doesn’t beeb like in your Video I will record a video tonight
>
> 8 Nis 2020 Çar, saat 09:27 tarihinde Hari Nair <notifications@github.com>
> şunu yazdı:
>
> > 1. Normal, there is sensor noise.2. You can't, the code in the loop
> > needs to execute within 2mS because of the sensor sample rate of 500Hz.
> > Print statements take a long time.
> > On Wednesday, 8 April, 2020, 11:21:51 am IST, gökhan erdal <
